# Generated by Django 4.2.7 on 2025-10-07 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Código único del módulo (ej: ventas, rrhh)', unique=True)),
                ('name', models.CharField(help_text='Nombre visible del módulo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del módulo')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono CSS (ej: bi-cart para Bootstrap Icons)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='¿El módulo está activo?')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización en menús')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descripción del rol')),
                ('is_client_role', models.BooleanField(default=True, help_text='¿Es un rol de cliente? (False = rol interno de EcoEnergy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(help_text='Grupo de Django asociado', on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, help_text='RUT del usuario (sin puntos, con guión)', max_length=12, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Teléfono del usuario', max_length=20)),
                ('position', models.CharField(blank=True, help_text='Cargo en la empresa', max_length=100)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='Empresa a la que pertenece el usuario', on_delete=django.db.models.deletion.PROTECT, to='monitoring.organization')),
                ('user', models.OneToOneField(help_text='Usuario de Django', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, help_text='Puede ver/listar')),
                ('can_add', models.BooleanField(default=False, help_text='Puede agregar')),
                ('can_change', models.BooleanField(default=False, help_text='Puede modificar')),
                ('can_delete', models.BooleanField(default=False, help_text='Puede eliminar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(help_text='Módulo', on_delete=django.db.models.deletion.CASCADE, related_name='role_perms', to='usuarios.module')),
                ('role', models.ForeignKey(help_text='Rol', on_delete=django.db.models.deletion.CASCADE, related_name='module_perms', to='usuarios.role')),
            ],
            options={
                'verbose_name': 'Permiso Rol-Módulo',
                'verbose_name_plural': 'Permisos Rol-Módulo',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
